
artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/10TzgAhncmVvryDkKTc9OE6F_KHgjDnyb/view?usp=sharing
  local_data_file: artifacts/data_ingestion/chest-ct-scan-images.zip
  extract_dir: artifacts/data_ingestion
